✨ [Feature] 게시물 목록 조회 API, 게시물 상세 조회 API 구현
wanted-pre-ob/social-feed-hub pull request #21
Opened 2024-08-26 11:28 UTC by ooheunda

## Summary

`GET api/postings` 게시물 목록 조회 API  
`GET api/postings/:id` 게시물 상세 조회 API  
구현했습니다.  
[Notion TIL](https://www.notion.so/240826-ae6dc29d19894562a92663a6f93effd5) 함께 봐주시면 좋을 것 같습니다!!! (의문 폭격)

## Describe your changes
- `postings.module`, `postings.controller`, `postings.service` 파일 생성해 비즈니스 로직 작성 했습니다.
- API 구현에 필요한 `posting-query.dto` `posting-response.dto` 파일 생성했습니다.
- `posting.entity`의 enum값 youtube -> threads로 변경했습니다.
- 예외처리 `400`은 dto 선에서 class-validator로, `401`은 추후 User feature 머지 시 가드 적용할 예정입니다.
- **`dev` -> `feature/posting` pull 받을때 rebase 사용해보았습니다**

## Issue number and link

목록 조회 #12 
상세 조회 #13

2024-08-26 11:42 UTC, ooheunda commented on src/postings/dto/posting-query.dto.ts
> +  @IsNotEmpty()
default값 서비스 로직에서 적용

2024-08-26 12:02 UTC, ooheunda commented on src/postings/dto/posting-query.dto.ts
> +  @IsNotEmpty()
Pipe 코드 빼먹어서 안된거였습니다...
그러나!! number query들은 number type으로 형 변환해주기

2024-08-26 13:54 UTC, jis-kim requested changes
리뷰 확인 부탁드립니다~!

2024-08-26 13:54 UTC, jis-kim commented on database/data-source.ts
`/database` 파일들이 왜 있을까요...??

2024-08-26 13:54 UTC, jis-kim commented on src/postings/postings.service.ts
> +      .where('hashtag.name = :hashtag', { hashtag });
이 부분은 회의에서 설명드린 대로 repository + relations 옵션으로 처리 가능할 듯 합니다.

2024-08-26 13:54 UTC, jis-kim commented on src/postings/postings.service.ts
> +      .getMany();
여기도 repository 에 pagination 관련 옵션들이 있습니다. [참고](https://typeorm.io/find-options)
`take`, `skip` 똑같이 있으니 적용해서 변경하시면 될 것 같아요.

2024-08-26 13:54 UTC, jis-kim commented on src/postings/postings.service.ts
> +      .getMany();
쿼리가 여기까지 하나군요.....??
여기 있는 요소들이 다 `repository`에 있긴 한데 이렇게 조건이 나뉘어서 query build 하는 과정이 있으면 `queryBuilder` 사용하시고 쿼리를 만드는 함수를 따로 빼서 정의해도 괜찮을 것 같습니다.

2024-08-26 13:54 UTC, jis-kim commented on src/postings/postings.service.ts
> +    if (!posting) {
```suggestion
    if (posting !== null) {
```
명확하게 체크하는 방향으로 수정 부탁드립니다.

2024-08-26 15:52 UTC, ooheunda commented on database/data-source.ts
dev에서 풀땡길때 rebase로 머지해서 지수님께서 #18 에 작업하신 부분이 포함된 것 같습니다!

2024-08-28 01:30 UTC, jis-kim commented on src/postings/postings.controller.ts
> +  @UseGuards(AuthGuard('jwt'))
이 부분 global 로 이미 처리되어있어 빼도 될 것 같습니다

2024-08-28 14:03 UTC, joosomi submitted a review, later dismissed
수고하셨습니다!

2024-08-28 15:21 UTC, jis-kim commented on src/postings/postings.service.ts
> +    }
```suggestion
const hashtags: string[] = postingObj.postingHashtags.map(postingHashtag) => postingHashtag.hashtag.name);
```
참고용 suggestion : `map`을 사용하면 return 으로 바로 새 배열을 생성할 수 있습니다. 앗 위에 `findAll` 에서는 `map`을 사용하셨는데 여기서는  `forEach` 사용하신 이유가 혹시 있을까요?
그리고 length 체크 로직 사용한 이유가 있으신가요? length가 0이면 `forEach()` 실행이 안되는 걸로 알아서 의미 없는 부분같은데 특별한 이유가 있으신지 궁금합니다.

2024-08-28 15:23 UTC, jis-kim commented on src/postings/postings.service.ts
> +  private async getRawPostings(hashtag: string, queries: PostingQueryDto): Promise<Posting[]> {
분리 해주신 거 좋아요우

2024-08-28 15:23 UTC, jis-kim submitted a review, later dismissed
코멘트를 남겼으나 큰 문제가 아니기에 approve를 드립니다. 고생하셨어요~!!

2024-08-29 02:19 UTC, ooheunda commented on src/postings/postings.service.ts
> +    }
말씀 주신 두 부분이 같이 가는거라, length 체크를 위해 `map` 대신 `forEach`를 사용했습니다.
그러나 특별한 이유는 없었습니다... `v.hashtag.name` 할 때 객체에 없는 키값 읽는 에러 피하려고 썼던건데, 0이면 메서드 내에서도 그냥 넘어간다는걸 이땐 잊고 있었네요;; 감사합니다!!

2024-08-29 04:25 UTC, joosomi approved these changes

2024-08-29 04:30 UTC, kimdoyeonn approved these changes

2024-08-29 04:30 UTC, jis-kim approved these changes
approve 뒤에 푸시되면 approve가 없어지는 옵션을 없앴습니다...ㅎㅎ

2024-08-29 04:41 UTC, merged