✨[Feature] 게시물 좋아요/공유하기 API 구현
wanted-pre-ob/social-feed-hub pull request #22
Opened 2024-08-26 12:01 UTC by joosomi

## Summary
- 좋아요 API
- 공유하기 API
## Describe your changes

## Issue number and link
#15 
#16

2024-08-26 12:09 UTC, joosomi commented on src/postings/postings.service.ts
> +      throw new NotFoundException('존재하지 않는 게시글입니다.');
에러 메시지 영어로 수정

2024-08-26 12:09 UTC, jis-kim requested changes
코멘트 확인 부탁드립니다.

2024-08-26 12:09 UTC, jis-kim commented on src/postings/postings.service.ts
> +    await this.postingRepository.update(id, { likeCount: newLikeCount });
update 결과가 response 에 필요없으므로 `await` 을 빼고 비동기 처리해도 될 것 같습니다.

2024-08-26 12:09 UTC, jis-kim commented on src/postings/postings.controller.ts
> +  @HttpCode(204) //성공시 204 No Content
`HttpStatus.NO_CONTENT` 사용해주세요.

2024-08-26 12:09 UTC, jis-kim commented on src/postings/postings.service.ts
> +    await this.postingRepository.update(id, { shareCount: newShareCount });
여기도 마찬가지로 비동기 처리 해도 될 것 같습니다.

2024-08-27 05:16 UTC, ooheunda submitted a review, later dismissed
고생하셨습니다! 👍

2024-08-27 06:02 UTC, jis-kim commented
수정사항 확인했습니다~! 고생하셨어요

2024-08-27 06:02 UTC, jis-kim submitted a review, later dismissed

2024-08-28 15:28 UTC, jis-kim approved these changes, later dismissed
이거 왜 approve 취소되어있죠..?!

2024-08-28 16:14 UTC, joosomi commented
> 이거 왜 approve 취소되어있죠..?!

검색해보니 새로운 커밋이 push 되었을 때 기존 Approve가 무효화되는게 아닐까 싶습니다..! 허허

2024-08-29 04:30 UTC, ooheunda approved these changes

2024-08-29 08:28 UTC, jis-kim approved these changes
readme가 너무 깔끔해서 눈물을 흘렸습니다..

2024-08-29 08:31 UTC, merged